from time import sleep

from selenium import webdriver

from Common.userlogin import Loginuser
from Tools.name import  pro
from Tools.number import numer1, numer2, day1, day2


class Test_risk():
    # 产品配置
    # def test_login(self):
    #     driver = webdriver.Chrome()
    #     Loginuser().login(driver)
    #     driver.find_element_by_xpath("(//span[contains(text(),'产品配置')])[1]").click()
    #     sleep(1)
    #     driver.find_element_by_xpath("//span[contains(text(),'新建产品')]").click()
    #     sleep(1)
    #     driver.find_element_by_xpath("//input[@placeholder='请输入产品名称']").send_keys(pro())
    #     sleep(1)
    #     driver.find_element_by_xpath("//label[contains(text(),'授信额度')]/following-sibling::div//input").send_keys(numer1)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'授信额度')]/following-sibling::div//input[@class='el-input__inner'])[2]").send_keys(numer2)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'授信额度')]/following-sibling::div//input[@class='el-input__inner'])[3]").send_keys(numer1)
    #     sleep(1)
    #     driver.find_element_by_xpath("//label[contains(text(),'费率1')]/following-sibling::div//input").send_keys(numer1)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'费率1')]/following-sibling::div//input[@class='el-input__inner'])[2]").send_keys(numer2)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'费率1')]/following-sibling::div//input[@class='el-input__inner'])[3]").send_keys(numer1)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//span[contains(text(),'新建')])[3]").click()
    #     sleep(1)
    #     driver.find_element_by_xpath("//label[contains(text(),'费率2')]/following-sibling::div//input").send_keys(numer1)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'费率2')]/following-sibling::div//input[@class='el-input__inner'])[2]").send_keys(numer2)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'费率2')]/following-sibling::div//input[@class='el-input__inner'])[3]").send_keys(numer1)
    #     sleep(1)
    #     driver.find_element_by_xpath("//label[contains(text(),'借款周期')]/following-sibling::div//input").send_keys(day1)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'借款周期')]/following-sibling::div//input[@class='el-input__inner'])[3]").send_keys(day2)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'借款周期')]/following-sibling::div//input[@class='el-input__inner'])[4]").send_keys(day1)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//span[@class='el-radio__inner'])[1]").click()
    #     sleep(1)
    #     driver.find_element_by_xpath("//input[@placeholder='请输入备注信息']").send_keys("欢迎使用我们的产品！")
    #     sleep(1)
    #     driver.find_element_by_xpath("(//span[contains(text(),'确 定')])[3]").click()
    #     sleep(2)
    #     # 编辑产品
    #     driver.find_element_by_xpath("//span[contains(text(),'编辑')]").click()
    #     sleep(1)
    #     driver.find_element_by_xpath("//input[@placeholder='请输入产品名称']").clear()
    #     driver.find_element_by_xpath("//input[@placeholder='请输入产品名称']").send_keys(pro())
    #     sleep(1)
    #     driver.find_element_by_xpath("//label[contains(text(),'授信额度')]/following-sibling::div//input").clear()
    #     driver.find_element_by_xpath("//label[contains(text(),'授信额度')]/following-sibling::div//input").send_keys(numer1)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'授信额度')]/following-sibling::div//input)[2]").clear()
    #     driver.find_element_by_xpath("(//label[contains(text(),'授信额度')]/following-sibling::div//input)[2]").send_keys(numer2)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'授信额度')]/following-sibling::div//input)[3]").clear()
    #     driver.find_element_by_xpath("(//label[contains(text(),'授信额度')]/following-sibling::div//input)[3]").send_keys(numer1)
    #     sleep(1)
    #     driver.find_element_by_xpath("//label[contains(text(),'费率1')]/following-sibling::div//input").clear()
    #     driver.find_element_by_xpath("//label[contains(text(),'费率1')]/following-sibling::div//input").send_keys(numer1)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'费率1')]/following-sibling::div//input)[2]").clear()
    #     driver.find_element_by_xpath("(//label[contains(text(),'费率1')]/following-sibling::div//input)[2]").send_keys(numer2)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'费率1')]/following-sibling::div//input)[3]").clear()
    #     driver.find_element_by_xpath("(//label[contains(text(),'费率1')]/following-sibling::div//input)[3]").send_keys(numer1)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//i[@class='el-select__caret el-input__icon el-icon-arrow-up'])[2]").click()
    #     sleep(1)
    #     driver.find_element_by_xpath("//span[contains(text(),'日')]").click()
    #     sleep(1)
    #     driver.find_element_by_xpath("//label[contains(text(),'借款周期')]/following-sibling::div//input").clear()
    #     driver.find_element_by_xpath("//label[contains(text(),'借款周期')]/following-sibling::div//input").send_keys(day1)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'借款周期')]/following-sibling::div//input)[3]").clear()
    #     driver.find_element_by_xpath("(//label[contains(text(),'借款周期')]/following-sibling::div//input)[3]").send_keys(day2)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//label[contains(text(),'借款周期')]/following-sibling::div//input)[4]").clear()
    #     driver.find_element_by_xpath("(//label[contains(text(),'借款周期')]/following-sibling::div//input)[4]").send_keys(day1)
    #     sleep(1)
    #     driver.find_element_by_xpath("(//span[@class='el-radio__inner'])[2]").click()
    #     sleep(1)
    #     driver.find_element_by_xpath("//input[@placeholder='请输入备注信息']").clear()
    #     driver.find_element_by_xpath("//input[@placeholder='请输入备注信息']").send_keys("欢迎您使用我们的借贷产品！")
    #     sleep(1)
    #     driver.find_element_by_xpath("(//span[contains(text(),'确 定')])[3]").click()
    #     sleep(1)
    #     # 关联字段
    #     driver.find_element_by_xpath("//span[contains(text(),'必备字段')]").click()
    #     sleep(1)
    #     driver.find_element_by_xpath("(//i[@class='el-select__caret el-input__icon el-icon-arrow-up'])[2]").click()
    #     sleep(1)
    #     driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list'])[2]/li").click()
    #     sleep(1)
    #     driver.find_element_by_xpath("//div[@class='el-select__tags']").click()
    #     sleep(2)
    #     driver.find_element_by_xpath("(//span[contains(text(),'确 定')])[2]").click()
    #     sleep(2)
    #     driver.quit()

    # 渠道配置
    def test_chennl(self):
        driver = webdriver.Chrome()
        Loginuser().login(driver)
        driver.find_element_by_xpath("//span[contains(text(),'渠道配置')]").click()
        sleep(1)
        driver.find_element_by_xpath("//span[contains(text(),'新建渠道')]").click()
        sleep(2)