import time
from time import sleep
import pytest
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

from Common.conf import password, username, start_date, start_time, start_dates, start_times, merchant_name, \
    merchant_id, UID, original_id, userid, suerphone, username1, imgpath, merchant_username, merchantid, credit_code, \
    merchant_start_date, merchant_start_time, merchant_end_time, end_time, login_end_time, role_user, operator_account, \
    operator_username, merchant_phone, merchant_img, merchant_password, menu_icon, menu_name, menu_path, menu_icons, \
    menu_names, menu_paths
from Tools.email import generate_random_email
from Tools.name import usernames, make_name, company, make_names, user
from Tools.number import day1, day2, num
from Tools.passwrod import GenPassword
from Tools.phone import random_phone


class Test_live():
    
    def test_login(self):
        url= 'https://boss-test.runx.com/login'
        driver = webdriver.Chrome()
        driver.get(url)
        driver.maximize_window()
        # driver.implicitly_wait(10)
        try:
            driver.find_element_by_xpath("//input[@name='username']").send_keys(username)
            sleep(2)
            driver.find_element_by_xpath("//input[@name='password']").send_keys(password)
            sleep(2)
            driver.find_element_by_xpath("//span[contains(text(),'登录')]").click()
            sleep(3)
            try:
                driver.find_element_by_xpath("//span[contains(text(),'权限管理')]").click()
                sleep(1)
            except :
                driver.refresh()
                sleep(1)
                driver.find_element_by_xpath("//input[@name='username']").send_keys(username)
                sleep(2)
                driver.find_element_by_xpath("//input[@name='password']").send_keys(password)
                sleep(2)
                driver.find_element_by_xpath("//span[contains(text(),'登录')]").click()
                sleep(3)
                driver.find_element_by_xpath("//span[contains(text(),'权限管理')]").click()
                sleep(1)
            # 权限管理
            driver.find_element_by_xpath("//span[contains(text(),'角色管理')]").click()
            sleep(1)
            # 新增角色
            driver.find_element_by_xpath("(//span[contains(text(),'新增角色')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//input[@placeholder='请输入角色名称'])[2]").send_keys(user())
            sleep(1)
            driver.find_element_by_xpath("(//i[@class='el-select__caret el-input__icon el-icon-arrow-up'])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list']/li)[7]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
            sleep(1)
            # 编辑角色
            driver.refresh()
            sleep(2)
            driver.find_element_by_xpath("(//span[contains(text(),'编辑')])[1]").click()
            sleep(2)
            driver.find_element_by_xpath("(//input[@placeholder='请输入角色名称'])[2]").clear()
            sleep(1)
            driver.find_element_by_xpath("(//input[@placeholder='请输入角色名称'])[2]").send_keys(user())
            sleep(1)
            driver.find_element_by_xpath("(//i[@class='el-select__caret el-input__icon el-icon-arrow-up'])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list']/li)[6]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
            sleep(1)
            # 角色授权
            driver.refresh()
            sleep(2)
            driver.find_element_by_xpath("(//span[contains(text(),'授权')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-checkbox__inner'])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-tree-node__expand-icon el-icon-caret-right'])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-checkbox__inner'])[3]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-checkbox__inner'])[5]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-checkbox__inner'])[7]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'保存')]").click()
            sleep(1)
            # 搜索
            driver.find_element_by_xpath("//input[@placeholder='请输入角色名称']").send_keys(role_user)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入角色名称']").clear()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 翻頁
            driver.find_element_by_xpath("(//li[@class='number'])[3]").click()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-left']").click()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-right']").click()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-select__caret el-input__icon el-icon-arrow-up']").click()
            sleep(1)
            driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list']/li)[2]").click()
            sleep(1)
            js = "window.scrollTo(100, document.body.scrollHeight)"
            driver.execute_script(js)
            sleep(1)
            driver.find_element_by_xpath("(//input[@class='el-input__inner'])[3]").send_keys(day1)
            sleep(1)
            # 操作员管理
            driver.find_element_by_xpath("//span[contains(text(),'操作员管理')]").click()
            sleep(1)
            # 新增账号
            driver.find_element_by_xpath("//span[contains(text(),'新增账号')]").click()
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'操作员账号:')]/following-sibling::div//input").send_keys(usernames())
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'操作员姓名:')]/following-sibling::div//input").send_keys(make_name())
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'登录密码:')]/following-sibling::div//input").send_keys(GenPassword())
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'手机号:')]/following-sibling::div//input").send_keys(random_phone())
            sleep(1)
            driver.find_element_by_xpath("(//i[@class='el-select__caret el-input__icon el-icon-arrow-up'])[2]").click()
            sleep(1)
            element11 = driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list']/li)[62]")
            ActionChains(driver).move_to_element(element11).click(element11).perform()
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'操作员角色:')]/following-sibling::div//div").click()
            sleep(1)
            driver.find_element_by_xpath("((//ul[@class='el-scrollbar__view el-select-dropdown__list'])[3]/li)[1]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
            sleep(1)
            # 编辑账号
            driver.refresh()
            sleep(2)
            driver.find_element_by_xpath("(//span[contains(text(),'编辑')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'操作员姓名:')]/following-sibling::div//input").clear()
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'操作员姓名:')]/following-sibling::div//input").send_keys(make_name())
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'重置')]").click()
            sleep(2)
            driver.find_element_by_xpath("//input[@placeholder='请设置操作员密码']").send_keys(GenPassword())
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'手机号:')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'手机号:')]/following-sibling::div//input").send_keys(random_phone())
            sleep(1)
            driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list']/li)[67]").click()
            sleep(1)
            # driver.find_element_by_xpath("//div[@class='el-select__tags']").click()
            # sleep(1)
            driver.find_element_by_xpath("(//i[@class='el-select__caret el-input__icon el-icon-arrow-up'])[3]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'启用')]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
            sleep(1)
            # 搜索
            driver.find_element_by_xpath("(//input[@placeholder='请输入操作员账号'])[1]").send_keys(operator_account)
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入姓名']").send_keys(operator_username)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("(//input[@placeholder='请输入操作员账号'])[1]").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入姓名']").clear()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 翻页
            driver.find_element_by_xpath("(//li[@class='number'])[3]").click()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-left']").click()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-right']").click()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-select__caret el-input__icon el-icon-arrow-up']").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'100条/页')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@class='el-input__inner']").send_keys(day2)
            driver.find_element_by_xpath("//input[@class='el-input__inner']").send_keys(Keys.ENTER)
            sleep(1)
            # 菜单管理
            driver.find_element_by_xpath("(//span[contains(text(),'菜单管理')])[1]").click()
            sleep(1)
            # 新增菜单
            driver.find_element_by_xpath("//span[contains(text(),'新增菜单')]").click()
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'菜单图标')]/following-sibling::div//input").send_keys(menu_icon)
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'菜单标题')]/following-sibling::div//input").send_keys(menu_name)
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'路由地址')]/following-sibling::div//input").send_keys(menu_path)
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'排序')]/following-sibling::div//input").send_keys(day2)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
            sleep(2)
            # 编辑主菜单
            driver.refresh()
            sleep(2)
            driver.find_element_by_xpath("//*[@id='app']/div/div[2]/section/div/div[1]/div[2]/div[4]/div[2]/table/tbody/tr[14]/td[7]/div/button[1]/span").click()
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'菜单图标')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'菜单图标')]/following-sibling::div//input").send_keys(menu_icon)
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'菜单标题')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'菜单标题')]/following-sibling::div//input").send_keys(menu_name)
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'路由地址')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'路由地址')]/following-sibling::div//input").send_keys(menu_path)
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'排序')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'排序')]/following-sibling::div//input").send_keys(day1)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
            sleep(1)
            # 新增子菜单
            driver.refresh()
            sleep(2)
            driver.find_element_by_xpath("(//span[contains(text(),'新增菜单')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-radio-button__inner'])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'菜单图标')]/following-sibling::div//input").send_keys(menu_icons)
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'菜单标题')]/following-sibling::div//input").send_keys(menu_names)
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'路由地址')]/following-sibling::div//input").send_keys(menu_paths)
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'排序')]/following-sibling::div//input").send_keys(day1)
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-radio-button__inner'])[3]").click()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-input__icon el-icon-arrow-down']").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-radio__inner'])[5]").click()
            sleep(1)
            driver.find_element_by_xpath("//div[@class='el-input el-input--suffix is-focus']").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
            sleep(1)
            # 编辑子菜单
            driver.refresh()
            sleep(2)
            driver.find_element_by_xpath("(//div[@class='el-table__expand-icon'])[5]").click()
            sleep(2)
            button   = driver.find_element_by_xpath("(//span[contains(text(),'编辑')])[15]")
            ActionChains(driver).move_to_element(button).click(button).perform()
            sleep(3)
            driver.find_element_by_xpath("//label[contains(text(),'菜单标题')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'菜单标题')]/following-sibling::div//input").send_keys(menu_names)
            sleep(2)
            driver.find_element_by_xpath("//label[contains(text(),'路由地址')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'路由地址')]/following-sibling::div//input").send_keys(menu_paths)
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'排序')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'排序')]/following-sibling::div//input").send_keys(day1)
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-radio-button__inner'])[4]").click()
            sleep(1)
            # driver.find_element_by_xpath("//i[@class='el-input__icon el-icon-arrow-down']").click()
            # sleep(1)
            # driver.find_element_by_xpath("(//span[@class='el-radio__inner'])[1]").click()
            # sleep(1)
            try:
                driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
                sleep(2)
            except:
                driver.find_element_by_xpath("//i[@class='el-dialog__close el-icon el-icon-close']").click()
                sleep(1)
            # 商户管理/商户信息
            driver.find_element_by_xpath("(//span[contains(text(),'商户管理')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'商户信息')])[1]").click()
            sleep(1)
            # 新增商户
            driver.find_element_by_xpath("(//span[contains(text(),'新增商户')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'企业名称:')]/following-sibling::div//input").send_keys(company())
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'社会统一信用代码:')]/following-sibling::div//input").send_keys(num)
            sleep(1)
            try:
                driver.find_element_by_xpath("//input[@name='file']").send_keys(merchant_img)
                sleep(4)
            except:
                driver.find_element_by_xpath("//input[@name='file']").send_keys(merchant_img)
                sleep(4)
            driver.find_element_by_xpath("//label[contains(text(),'联系人:')]/following-sibling::div//input").send_keys(make_name())
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'联系人手机号:')]/following-sibling::div//input").send_keys(random_phone())
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'联系人邮箱:')]/following-sibling::div//input").send_keys(generate_random_email())
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'登录密码:')]/following-sibling::div//input").send_keys(merchant_password)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
            sleep(1)
            # 详情
            driver.refresh()
            sleep(2)
            element1 = driver.find_element_by_xpath("(//span[contains(text(),'详情')])[1]")
            ActionChains(driver).move_to_element(element1).click(element1).perform()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-dialog__close el-icon el-icon-close']").click()
            sleep(1)
            # 编辑商户
            driver.refresh()
            sleep(2)
            element2 = driver.find_element_by_xpath("(//span[contains(text(),'编辑')])[1]")
            ActionChains(driver).move_to_element(element2).click(element2).perform()
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'企业名称:')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'企业名称:')]/following-sibling::div//input").send_keys(company())
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'社会统一信用代码:')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'社会统一信用代码:')]/following-sibling::div//input").send_keys(num)
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-icon-delete']").click()
            driver.find_element_by_xpath("//input[@name='file']").send_keys(imgpath)
            sleep(4)
            driver.find_element_by_xpath("//label[contains(text(),'联系人:')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'联系人:')]/following-sibling::div//input").send_keys(make_name())
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'联系人手机号:')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'联系人手机号:')]/following-sibling::div//input").send_keys(random_phone())
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'联系人邮箱:')]/following-sibling::div//input").clear()
            driver.find_element_by_xpath("//label[contains(text(),'联系人邮箱:')]/following-sibling::div//input").send_keys(generate_random_email())
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
            sleep(1)
            # 重置密码
            driver.refresh()
            sleep(2)
            element3 = driver.find_element_by_xpath("(//span[contains(text(),'重置密码')])[1]")
            ActionChains(driver).move_to_element(element3).click(element3).perform()
            sleep(1)
            driver.find_element_by_xpath("//label[contains(text(),'登录密码')]/following-sibling::div//input").send_keys(GenPassword())
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
            sleep(1)
            # 商户名称搜索
            driver.find_element_by_xpath("//input[@placeholder='请输入商户名称']").send_keys(merchant_username)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 商户ID搜索
            driver.find_element_by_xpath("//input[@placeholder='请输入商户ID']").send_keys(merchantid)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 信用代码搜索
            driver.find_element_by_xpath("//input[@placeholder='请输入社会统一信用代码']").send_keys(credit_code)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 手机号搜索
            driver.find_element_by_xpath("//input[@placeholder='请输入联系人手机号']").send_keys(merchant_phone)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 注册时间搜索
            driver.find_element_by_xpath("//input[@placeholder='开始日期']").click()
            sleep(1)
            driver.find_element_by_xpath("(//input[@placeholder='开始日期'])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//input[@placeholder='开始日期'])[2]").send_keys(merchant_start_date)
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='开始时间']").clear()
            sleep(2)
            driver.find_element_by_xpath("//input[@placeholder='开始时间']").send_keys(merchant_start_time)
            sleep(5)
            driver.find_element_by_xpath("(//button[contains(text(),'确定')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='结束时间']").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='结束时间']").send_keys(merchant_end_time)
            sleep(1)
            driver.find_element_by_xpath("(//button[contains(text(),'确定')])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),' 确定')]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 商户性质搜索
            driver.find_element_by_xpath("//input[@placeholder='请选择']").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'企业')]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 为空搜索
            driver.find_element_by_xpath("//input[@placeholder='请输入商户名称']").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入商户ID']").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入社会统一信用代码']").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入联系人手机号']").clear()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-input__icon el-range__close-icon']").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # # 翻页
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-right']").click()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-left']").click()
            sleep(1)
            driver.find_element_by_xpath("(//i[@class='el-select__caret el-input__icon el-icon-arrow-up'])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list']/li)[5]").click()
            sleep(1)
            # 产品配置
            # 搜索
            driver.find_element_by_xpath("//span[contains(text(),'产品配置')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入商户ID']").send_keys("10000")
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入应用ID']").send_keys("APP1595397893301")
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'权限配置')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-checkbox__inner'])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'保存')]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'  确定')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入商户ID']").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入应用ID']").clear()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # # 翻页
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-right']").click()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-left']").click()
            sleep(1)
            driver.find_element_by_xpath("//span[@class='el-input__suffix-inner']").click()
            sleep(1)
            driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list']/li)[5]").click()
            sleep(1)
            driver.find_element_by_xpath("(//input[@class='el-input__inner'])[4]").send_keys(day2)
            sleep(1)
            # 控台配置
            driver.find_element_by_xpath("(//span[contains(text(),'控台配置')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'权限配置')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-checkbox__inner'])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-checkbox__inner'])[14]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'保存')]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),' 确定')]").click()
            sleep(1)
            # 搜索
            driver.find_element_by_xpath("//input[@placeholder='请输入商户ID']").send_keys("10030")
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入商户ID']").clear()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 翻页
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-right']").click()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-left']").click()
            sleep(1)
            driver.find_element_by_xpath("//span[@class='el-input__suffix-inner']").click()
            sleep(1)
            driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list']/li)[3]").click()
            sleep(1)
            driver.find_element_by_xpath("(//input[@class='el-input__inner'])[3]").send_keys(day2)
            driver.find_element_by_xpath("(//input[@class='el-input__inner'])[3]").send_keys(Keys.ENTER)
            sleep(1)
            # 商户菜单
            driver.find_element_by_xpath("//span[contains(text(),'商户菜单管理')]").click()
            sleep(1)
            # 用户管理
            driver.find_element_by_xpath("(//span[contains(text(),'用户管理')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'用户信息')])[1]").click()
            sleep(1)
            #封禁
            element7 = driver.find_element_by_xpath("(//button[@type='button'])[2]")
            ActionChains(driver).move_to_element(element7).click(element7).perform()
            sleep(3)
            driver.find_element_by_xpath("//span[contains(text(),' 确定')]").click()
            sleep(1)
            # 搜索
            driver.find_element_by_xpath("//input[@placeholder='请输入商户名称']").send_keys(merchant_name)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入商户ID']").send_keys(merchant_id)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入UID']").send_keys(UID)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入原始ID']").send_keys(original_id)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入userid']").send_keys(userid)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入用户昵称']").send_keys(username1)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入用户手机号']").send_keys(suerphone)
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 注册时间
            driver.find_element_by_xpath("(//input[@placeholder='开始日期'])[1]").click()
            sleep(2)
            driver.find_element_by_xpath("(//input[@placeholder='开始日期'])[4]").send_keys(start_date)
            sleep(2)
            driver.find_element_by_xpath("//input[@placeholder='开始时间']").clear()
            driver.find_element_by_xpath("//input[@placeholder='开始时间']").send_keys(start_time)
            sleep(2)
            driver.find_element_by_xpath("(//button[contains(text(),'确定')])[1]").click()
            sleep(2)
            driver.find_element_by_xpath("//input[@placeholder='结束时间']").clear()
            driver.find_element_by_xpath("//input[@placeholder='结束时间']").send_keys(end_time)
            sleep(1)
            driver.find_element_by_xpath("(//button[contains(text(),'确定')])[2]").click()
            sleep(1)
            try:
                driver.find_element_by_xpath("//span[contains(text(),'  确定')]").click()
                sleep(2)
            except :
                driver.find_element_by_xpath("(//span[contains(text(),'  确定')])[2]").click()
                sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 用户商控状态
            driver.find_element_by_xpath("//input[@placeholder='请选择']").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'启用')])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请选择']").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'禁用')])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请选择']").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'全部')])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 获取userid时间
            driver.find_element_by_xpath("(//input[@placeholder='开始日期'])[2]").click()
            sleep(2)
            driver.find_element_by_xpath("(//input[@placeholder='开始日期'])[5]").send_keys(start_date)
            sleep(2)
            driver.find_element_by_xpath("(//input[@placeholder='开始时间'])[2]").clear()
            sleep(1)
            driver.find_element_by_xpath("(//input[@placeholder='开始时间'])[2]").send_keys(start_time)
            sleep(2)
            driver.find_element_by_xpath("(//button[contains(text(),'确定')])[3]").click()
            sleep(2)
            driver.find_element_by_xpath("(//input[@placeholder='结束时间'])[2]").clear()
            driver.find_element_by_xpath("(//input[@placeholder='结束时间'])[2]").send_keys(end_time)
            sleep(1)
            driver.find_element_by_xpath("(//button[contains(text(),'确定')])[4]").click()
            sleep(1)
            # try:
            driver.find_element_by_xpath("(//span[contains(text(),'    确定')])[2]").click()
            sleep(1)
            # except:
            #     driver.find_element_by_xpath("//span[contains(text(),'    确定')])").click()
            #     sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 用户最近登录时间
            driver.find_element_by_xpath("(//input[@placeholder='开始日期'])[3]").click()
            sleep(1)
            driver.find_element_by_xpath("(//input[@placeholder='开始日期'])[6]").send_keys(start_dates)
            sleep(1)
            driver.find_element_by_xpath("(//input[@placeholder='开始时间'])[3]").clear()
            driver.find_element_by_xpath("(//input[@placeholder='开始时间'])[3]").send_keys(start_times)
            sleep(1)
            driver.find_element_by_xpath("(//button[contains(text(),'确定')])[5]").click()
            sleep(1)
            driver.find_element_by_xpath("(//input[@placeholder='结束时间'])[3]").clear()
            driver.find_element_by_xpath("(//input[@placeholder='结束时间'])[3]").send_keys(login_end_time)
            sleep(1)
            driver.find_element_by_xpath("(//button[contains(text(),'确定')])[6]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),' 确定')])[3]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 用户状态状态
            driver.find_element_by_xpath("//span[contains(text(),'用户总台状态：')]/following-sibling::div//input").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'启用')])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'用户总台状态：')]/following-sibling::div//input").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'禁用')])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'用户总台状态：')]/following-sibling::div//input").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'全部')])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 为空搜索
            driver.find_element_by_xpath("//input[@placeholder='请输入商户名称']").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入商户ID']").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入UID']").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入原始ID']").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入userid']").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入用户昵称']").clear()
            sleep(1)
            driver.find_element_by_xpath("//input[@placeholder='请输入用户手机号']").clear()
            sleep(1)
            driver.find_element_by_xpath("(//i[@class='el-input__icon el-range__close-icon'])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//i[@class='el-input__icon el-range__close-icon'])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("(//i[@class='el-input__icon el-range__close-icon'])[3]").click()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'搜索')]").click()
            sleep(1)
            # 翻页
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-right']").click()
            sleep(1)
            driver.find_element_by_xpath("//i[@class='el-icon el-icon-arrow-left']").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[@class='el-input__suffix-inner'])[3]").click()
            sleep(1)
            driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list']/li)[11]").click()
            sleep(1)
            driver.find_element_by_xpath("(//input[@class='el-input__inner'])[11]").send_keys(day2)
            driver.find_element_by_xpath("(//input[@class='el-input__inner'])[11]").send_keys(Keys.ENTER)
            sleep(1)
            # 通用配置
            driver.find_element_by_xpath("//span[contains(text(),'通用配置')]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'供应商配置')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//span[contains(text(),'新增配置')])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//i[@class='el-select__caret el-input__icon el-icon-arrow-up'])[1]").click()
            sleep(1)
            driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list']/li)[2]").click()
            sleep(1)
            driver.find_element_by_xpath("(//i[@class='el-select__caret el-input__icon el-icon-arrow-up'])[2]").click()
            sleep(1)
            driver.find_element_by_xpath("(//ul[@class='el-scrollbar__view el-select-dropdown__list']/li)[2]").click()
            sleep(1)
            driver.find_element_by_xpath("//textarea[@placeholder='输入供应商配置文案']").send_keys()
            sleep(1)
            driver.find_element_by_xpath("//span[contains(text(),'确认')]").click()
            sleep(1)
        except Exception as message :
            print(u"异常原因%s"%message)
            nowTime = time.strftime("%Y%m%d.%H.%M.%S")
            t = driver.get_screenshot_as_file('%s.jpg'% nowTime)
            print(u"截图结果：%s"%t)
        driver.quit()

